export const DECK = [
  // Major Arcana
  { id: 'the-fool', name: 'The Fool', img: 'https://upload.wikimedia.org/wikipedia/commons/9/90/RWS_Tarot_00_Fool.jpg' },
  { id: 'the-magician', name: 'The Magician', img: 'https://upload.wikimedia.org/wikipedia/commons/d/de/RWS_Tarot_01_Magician.jpg' },
  { id: 'the-high-priestess', name: 'The High Priestess', img: 'https://upload.wikimedia.org/wikipedia/commons/8/88/RWS_Tarot_02_High_Priestess.jpg' },
  { id: 'the-empress', name: 'The Empress', img: 'https://upload.wikimedia.org/wikipedia/commons/9/96/The_Empress%2C_Waite-Smith_Tarot_Deck%2C_Yale_University.jpg' },
  { id: 'the-emperor', name: 'The Emperor', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/RWS_Tarot_04_Emperor.jpg/1024px-RWS_Tarot_04_Emperor.jpg' },
  { id: 'the-hierophant', name: 'The Hierophant', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/RWS_Tarot_05_Hierophant.jpg/1024px-RWS_Tarot_05_Hierophant.jpg' },
  { id: 'the-lovers', name: 'The Lovers', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/RWS_Tarot_06_Lovers.jpg/1024px-RWS_Tarot_06_Lovers.jpg' },
  { id: 'the-chariot', name: 'The Chariot', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/RWS_Tarot_07_Chariot.jpg/1024px-RWS_Tarot_07_Chariot.jpg' },
  { id: 'strength', name: 'Strength', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/RWS_Tarot_08_Strength.jpg/1024px-RWS_Tarot_08_Strength.jpg' },
  { id: 'the-hermit', name: 'The Hermit', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/RWS_Tarot_09_Hermit.jpg/1024px-RWS_Tarot_09_Hermit.jpg' },
  { id: 'wheel-of-fortune', name: 'Wheel of Fortune', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg/1024px-RWS_Tarot_10_Wheel_of_Fortune.jpg' },
  { id: 'justice', name: 'Justice', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/RWS_Tarot_11_Justice.jpg/1024px-RWS_Tarot_11_Justice.jpg' },
  { id: 'the-hanged-man', name: 'The Hanged Man', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/RWS_Tarot_12_Hanged_Man.jpg/1024px-RWS_Tarot_12_Hanged_Man.jpg' },
  { id: 'death', name: 'Death', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/RWS_Tarot_13_Death.jpg/1024px-RWS_Tarot_13_Death.jpg' },
  { id: 'temperance', name: 'Temperance', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/RWS_Tarot_14_Temperance.jpg/1024px-RWS_Tarot_14_Temperance.jpg' },
  { id: 'the-devil', name: 'The Devil', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/RWS_Tarot_15_Devil.jpg/1024px-RWS_Tarot_15_Devil.jpg' },
  { id: 'the-tower', name: 'The Tower', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/RWS_Tarot_16_Tower.jpg/1024px-RWS_Tarot_16_Tower.jpg' },
  { id: 'the-star', name: 'The Star', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/RWS_Tarot_17_Star.jpg/1024px-RWS_Tarot_17_Star.jpg' },
  { id: 'the-moon', name: 'The Moon', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/RWS_Tarot_18_Moon.jpg/1024px-RWS_Tarot_18_Moon.jpg' },
  { id: 'the-sun', name: 'The Sun', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/RWS_Tarot_19_Sun.jpg/1024px-RWS_Tarot_19_Sun.jpg' },
  { id: 'judgement', name: 'Judgement', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/RWS_Tarot_20_Judgement.jpg/1024px-RWS_Tarot_20_Judgement.jpg' },
  { id: 'the-world', name: 'The World', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/RWS_Tarot_21_World.jpg/1024px-RWS_Tarot_21_World.jpg' },
  
  // Cups
  { id: 'ace-of-cups', name: 'Ace of Cups', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Cups01.jpg/1024px-Cups01.jpg' },
  { id: '2-of-cups', name: 'Two of Cups', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Cups02.jpg/1024px-Cups02.jpg' },
  { id: '3-of-cups', name: 'Three of Cups', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Cups03.jpg/1024px-Cups03.jpg' },
  { id: '4-of-cups', name: 'Four of Cups', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Cups04.jpg/1024px-Cups04.jpg' },
  { id: '5-of-cups', name: 'Five of Cups', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Cups05.jpg/1024px-Cups05.jpg' },
  { id: '6-of-cups', name: 'Six of Cups', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Cups06.jpg/1024px-Cups06.jpg' },
  { id: '7-of-cups', name: 'Seven of Cups', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Cups07.jpg/1024px-Cups07.jpg' },
  { id: '8-of-cups', name: 'Eight of Cups', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Cups08.jpg/1024px-Cups08.jpg' },
  { id: '9-of-cups', name: 'Nine of Cups', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Cups09.jpg/1024px-Cups09.jpg' },
  { id: '10-of-cups', name: 'Ten of Cups', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Cups10.jpg/1024px-Cups10.jpg' },
  { id: 'page-of-cups', name: 'Page of Cups', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Cups11.jpg/1024px-Cups11.jpg' },
  { id: 'knight-of-cups', name: 'Knight of Cups', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Cups12.jpg/1024px-Cups12.jpg' },
  { id: 'queen-of-cups', name: 'Queen of Cups', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Cups13.jpg/1024px-Cups13.jpg' },
  { id: 'king-of-cups', name: 'King of Cups', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Cups14.jpg/1024px-Cups14.jpg' },

  // Pentacles
  { id: 'ace-of-pentacles', name: 'Ace of Pentacles', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Pents01.jpg/1024px-Pents01.jpg' },
  { id: '2-of-pentacles', name: 'Two of Pentacles', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Pents02.jpg/1024px-Pents02.jpg' },
  { id: '3-of-pentacles', name: 'Three of Pentacles', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Pents03.jpg/1024px-Pents03.jpg' },
  { id: '4-of-pentacles', name: 'Four of Pentacles', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Pents04.jpg/1024px-Pents04.jpg' },
  { id: '5-of-pentacles', name: 'Five of Pentacles', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Pents05.jpg/1024px-Pents05.jpg' },
  { id: '6-of-pentacles', name: 'Six of Pentacles', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Pents06.jpg/1024px-Pents06.jpg' },
  { id: '7-of-pentacles', name: 'Seven of Pentacles', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Pents07.jpg/1024px-Pents07.jpg' },
  { id: '8-of-pentacles', name: 'Eight of Pentacles', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Pents08.jpg/1024px-Pents08.jpg' },
  { id: '9-of-pentacles', name: 'Nine of Pentacles', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Pents09.jpg/1024px-Pents09.jpg' },
  { id: '10-of-pentacles', name: 'Ten of Pentacles', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Pents10.jpg/1024px-Pents10.jpg' },
  { id: 'page-of-pentacles', name: 'Page of Pentacles', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Pents11.jpg/1024px-Pents11.jpg' },
  { id: 'knight-of-pentacles', name: 'Knight of Pentacles', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Pents12.jpg/1024px-Pents12.jpg' },
  { id: 'queen-of-pentacles', name: 'Queen of Pentacles', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Pents13.jpg/1024px-Pents13.jpg' },
  { id: 'king-of-pentacles', name: 'King of Pentacles', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Pents14.jpg/1024px-Pents14.jpg' },

  //Swords
  { id: 'ace-of-swords', name: 'Ace of Swords', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Swords01.jpg/1024px-Swords01.jpg' },
  { id: '2-of-swords', name: 'Two of Swords', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Swords02.jpg/1024px-Swords02.jpg' },
  { id: '3-of-swords', name: 'Three of Swords', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Swords03.jpg/1024px-Swords03.jpg' },
  { id: '4-of-swords', name: 'Four of Swords', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Swords04.jpg/1024px-Swords04.jpg' },
  { id: '5-of-swords', name: 'Five of Swords', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Swords05.jpg/1024px-Swords05.jpg' },
  { id: '6-of-swords', name: 'Six of Swords', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Swords06.jpg/1024px-Swords06.jpg' },
  { id: '7-of-swords', name: 'Seven of Swords', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Swords07.jpg/1024px-Swords07.jpg' },
  { id: '8-of-swords', name: 'Eight of Swords', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Swords08.jpg/1024px-Swords08.jpg' },
  { id: '9-of-swords', name: 'Nine of Swords', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Swords09.jpg/1024px-Swords09.jpg' },
  { id: '10-of-swords', name: 'Ten of Swords', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Swords10.jpg/1024px-Swords10.jpg' },
  { id: 'page-of-swords', name: 'Page of Swords', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Swords11.jpg/1024px-Swords11.jpg' },
  { id: 'knight-of-swords', name: 'Knight of Swords', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Swords12.jpg/1024px-Swords12.jpg' },
  { id: 'queen-of-swords', name: 'Queen of Swords', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Swords13.jpg/1024px-Swords13.jpg' },
  { id: 'king-of-swords', name: 'King of Swords', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Swords14.jpg/1024px-Swords14.jpg' },

  //Wands
  { id: 'ace-of-wands', name: 'Ace of Wands', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Wands01.jpg/1024px-Wands01.jpg' },
  { id: '2-of-wands', name: 'Two of Wands', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Wands02.jpg/1024px-Wands02.jpg' },
  { id: '3-of-wands', name: 'Three of Wands', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Wands03.jpg/1024px-Wands03.jpg' },
  { id: '4-of-wands', name: 'Four of Wands', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Wands04.jpg/1024px-Wands04.jpg' },
  { id: '5-of-wands', name: 'Five of Wands', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Wands05.jpg/1024px-Wands05.jpg' },
  { id: '6-of-wands', name: 'Six of Wands', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Wands06.jpg/1024px-Wands06.jpg' },
  { id: '7-of-wands', name: 'Seven of Wands', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Wands07.jpg/250px-Wands07.jpg' },
  { id: '8-of-wands', name: 'Eight of Wands', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Wands08.jpg/1024px-Wands08.jpg' },
  { id: '9-of-wands', name: 'Nine of Wands', img: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/Tarot_Nine_of_Wands.jpg' },
  { id: '10-of-wands', name: 'Ten of Wands', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Wands10.jpg/1024px-Wands10.jpg' },
  { id: 'page-of-wands', name: 'Page of Wands', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Wands11.jpg/1024px-Wands11.jpg' },
  { id: 'knight-of-wands', name: 'Knight of Wands', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Wands12.jpg/1024px-Wands12.jpg' },
  { id: 'queen-of-wands', name: 'Queen of Wands', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Wands13.jpg/1024px-Wands13.jpg' },
  { id: 'king-of-wands', name: 'King of Wands', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Wands14.jpg/1024px-Wands14.jpg' },
];
